In [4]:
import pandas as pd

In [10]:
df = pd.read_csv('../data/consolidated_data/training_dataset.csv')
df.drop(columns=['Unnamed: 0'], inplace=True)

In [11]:
df.head()

,date,state,cases_new,cases_recovered,cases_active,cases_unvax,cases_pvax,cases_fvax,cases_0_4,cases_5_11,...,daily_partial,daily,admitted_covid_hospital,admitted_total_hospital,discharged_covid_hospital,discharged_total_hospital,hosp_covid_hospital,icu_covid,vent_covid,cases_new_capita
0,2020-01-25,Johor,4,0,4,4,0,0,0,0,...,0.0,0.0,6.0,11.0,5.0,9.0,28.0,2.0,1.0,0.000001
1,2020-01-25,Kedah,0,0,0,0,0,0,0,0,...,0.0,0.0,6.0,11.0,5.0,9.0,28.0,2.0,1.0,0.000000
2,2020-01-25,Kelantan,0,0,0,0,0,0,0,0,...,0.0,0.0,6.0,11.0,5.0,9.0,28.0,2.0,1.0,0.000000
3,2020-01-25,Melaka,0,0,0,0,0,0,0,0,...,0.0,0.0,6.0,11.0,5.0,9.0,28.0,2.0,1.0,0.000000
4,2020-01-25,Negeri Sembilan,0,0,0,0,0,0,0,0,...,0.0,0.0,6.0,11.0,5.0,9.0,28.0,2.0,1.0,0.000000

In [25]:
from statsmodels.tsa.stattools import adfuller

result = adfuller(df['cases_new'])
print(f'ADF Statistic: {result[0]}')
print(f'p-value: {result[1]}' )
print(f'Critical Values: {result[4]}')

ADF Statistic: -2.405630620507177
p-value: 0.14015351027001127
Critical Values: {'1%': -3.4306145729682744, '5%': -2.861656933183008, '10%': -2.5668322401244907}

In [31]:
split_index = int(0.8 * len(df))
df.drop(columns=['cases_new'],inplace=True)
train_data = df.iloc[:split_index]
test_data = df.iloc[split_index:]

print("Training data shape:", train_data.shape)

print("Testing data shape:", test_data.shape, test_data)

Training data shape: (19814, 27)
Testing data shape: (4954, 27)              date              state  cases_recovered  cases_active  \
19814  2023-06-16              Perak               45           782
19815  2023-06-16             Perlis                3            93
19816  2023-06-16       Pulau Pinang               39           605
19817  2023-06-16              Sabah                5          3791
19818  2023-06-16            Sarawak               56           686
...           ...                ...              ...           ...
24763  2024-04-20           Selangor                8            37
24764  2024-04-20         Terengganu                0           299
24765  2024-04-20  W.P. Kuala Lumpur                5           585
24766  2024-04-20        W.P. Labuan                0            28
24767  2024-04-20     W.P. Putrajaya                0           240

       cases_unvax  cases_pvax  cases_fvax  cases_0_4  cases_5_11  \
19814            4           1           6          1           1
19815            1           0           1          0           1
19816            2           0           9          0           2
19817            2           0           3          1           1
19818           10           0           5          3           2
...            ...         ...         ...        ...         ...
24763            4           0           8          0           3
24764            0           0           0          0           0
24765            6           0           3          2           1
24766            0           0           0          0           0
24767            0           0           0          0           0

       cases_12_17  ...  daily_partial  daily  admitted_covid_hospital  \
19814            1  ...            0.0   19.0                      1.0
19815            0  ...            0.0    0.0                      0.0
19816            0  ...           10.0   29.0                      7.0
19817            0  ...            2.0   12.0                     12.0
19818            2  ...            0.0   21.0                     12.0
...            ...  ...            ...    ...                      ...
24763            2  ...            0.0    3.0                      2.0
24764            0  ...            0.0    0.0                      1.0
24765            0  ...            2.0    3.0                      0.0
24766            0  ...            0.0    0.0                      0.0
24767            0  ...            0.0    0.0                      0.0

       admitted_total_hospital  discharged_covid_hospital  \
19814                      1.0                        4.0
19815                      0.0                        0.0
19816                      7.0                        8.0
19817                     44.0                       13.0
19818                     12.0                        7.0
...                        ...                        ...
24763                     22.0                        3.0
24764                      1.0                        0.0
24765                      0.0                        0.0
24766                      0.0                        0.0
24767                      4.0                        0.0

       discharged_total_hospital  hosp_covid_hospital  icu_covid  vent_covid  \
19814                        4.0                 10.0        0.0         0.0
19815                        0.0                  4.0        0.0         0.0
19816                        8.0                 12.0        1.0         1.0
19817                       56.0                 41.0        4.0         2.0
19818                        7.0                 36.0        4.0         4.0
...                          ...                  ...        ...         ...
24763                       25.0                  1.0        2.0         2.0
24764                        0.0                  1.0        0.0         0.0
24765                        0.0                  1.0        0.0         0.0
24766                        0.0                  0.0        0.0         0.0
24767                        2.0                  0.0        0.0         0.0

       cases_new_capita
19814          0.000015
19815          0.000016
19816          0.000027
19817          0.000004
19818          0.000016
...                 ...
24763          0.000006
24764          0.000000
24765          0.000019
24766          0.000000
24767          0.000026

[4954 rows x 27 columns]